// Code generated by goctl. DO NOT EDIT.
package types

type EmployeeInfoRequest struct {
	EmployeeId int64 `path:"id"`
}

type EmployeeInfoReply struct {
	EmployeeName string `form:"employeeName"`
}
