// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"WePublicMenu/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/menus-tree",
				Handler: QueryMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menus/sync",
				Handler: SyncMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menus",
				Handler: CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/menus",
				Handler: DeleteMenuHandler(serverCtx),
			},
		},
	)
}
